version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install

  pre_build:
    commands:
      - npm run lint

  build:
    commands:
      - npm run build
      - npm run test

artifacts:
  files:
    - '**/*'
  base-directory: build
